version: '3'

services:

  server:
    build:
      context: /server
      dockerfile: dockerfile
    ports:
      - 5051:5051

  getrecipe:
    build:
      context: /getRecipe
      dockerfile: dockerfile
    ports:
      - 80:80

  mysql_db:
    container_name: mysql_db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: qwerty

  db:
    depends_on:
      - mysql_db
    build:
      context: /getHistory
      dockerfile: dockerfile
    ports:
      - 3001:3001
    environment:
      MYSQL_HOST: mysql_db
      MYSQL_USER: root
      MYSQL_PASSWORD: qwerty
