version: '3'

services:

  server:
    depends_on:
      - keycloak
    build:
      context: /server
      dockerfile: dockerfile
    environment:
      KEYCLOAK_URL: http://host.docker.internal:8080/
    ports:
      - 5051:5051

  getrecipe:
    build:
      context: /getRecipe
      dockerfile: dockerfile
    ports:
      - 80:80

  mysql_db:
    container_name: mysql_db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: qwerty

  db:
    depends_on:
      - mysql_db
    build:
      context: /getHistory
      dockerfile: dockerfile
    ports:
      - 3001:3001
    environment:
      MYSQL_HOST: mysql_db
      MYSQL_USER: root
      MYSQL_PASSWORD: qwerty

  keycloak:
    container_name: keycloakapp
    volumes:
      - ./imports:/opt/jboss/keycloak/imports
    image: quay.io/keycloak/keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json
      KEYCLOAK_ADMIN: admin 
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: 
      - start-dev 